// Generates src/version.ts before every dev/build so the Sidebar can show
// a build identifier without hand-editing it each time (see the git log for
// what this replaced: manual "chore: bump sidebar version display" commits).
// Format: "3.0.<commit count> <5-char build code>", e.g. "3.0.144 K7XQP".
import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const outFile = resolve(__dirname, '../src/version.ts');

const MAJOR_MINOR = '3.0';

function getBuildNumber() {
  try {
    return execSync('git rev-list --count HEAD', { encoding: 'utf8' }).trim();
  } catch {
    return String(Date.now());
  }
}

function generateBuildCode(length = 5) {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  let code = '';
  for (let i = 0; i < length; i++) {
    code += chars[Math.floor(Math.random() * chars.length)];
  }
  return code;
}

const version = `${MAJOR_MINOR}.${getBuildNumber()}`;
const buildCode = generateBuildCode();

writeFileSync(
  outFile,
  `// Auto-generated by scripts/generate-version.js — do not edit by hand.\n` +
    `export const APP_VERSION = '${version}';\n` +
    `export const BUILD_CODE = '${buildCode}';\n`
);

console.log(`Generated ${outFile}: ${version} ${buildCode}`);
